Repository patrykswietlik/project-prestashop, pull requests merged in 2024-11, with the labels that each got.

#11 Added debug mode to defines.inc, fixed navabr styles based on target …
  config/devcontainer.json
  prestashop/html/.gitignore
  prestashop/html/config/defines.inc.php
  prestashop/html/themes/marvelTheme/assets/css/custom.css
  prestashop/html/themes/marvelTheme/config/theme.yml
  prestashop/html/themes/marvelTheme/preview.png
  prestashop/html/themes/marvelTheme/templates/_partials/header.tpl
  prestashop/html/themes/marvelTheme/templates/catalog/product.tpl
Labels: ui

#24 Add new quantity button/hot fixes
  .gitignore
  config/autoSaveToRepo.bat
  config/autoUploadToContainer.bat
  prestashop/html/themes/marvelTheme/assets/css/custom.css
  prestashop/html/themes/marvelTheme/assets/js/custom.js
  prestashop/html/themes/marvelTheme/templates/catalog/_partials/product-add-to-cart.tpl
  prestashop/html/themes/marvelTheme/templates/catalog/product.tpl
  prestashop/html/themes/marvelTheme/templates/layouts/layout-both-columns.tpl
Labels: enhancement

#26 Added tests
  tests/main.py
Labels: tests
